// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB22N7QWT_hfN8CVZGrpmXTAtvSYkP83Ts',
    appId: '1:295285705008:web:700fb81f83ca00356b60f5',
    messagingSenderId: '295285705008',
    projectId: 'book-companion-1',
    authDomain: 'book-companion-1.firebaseapp.com',
    databaseURL: 'https://book-companion-1-default-rtdb.firebaseio.com',
    storageBucket: 'book-companion-1.firebasestorage.app',
    measurementId: 'G-BYXE6HSE4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ65h17vdlRclkugxx7uvkB8QDOZE5TAo',
    appId: '1:295285705008:android:5c4704eaa11453096b60f5',
    messagingSenderId: '295285705008',
    projectId: 'book-companion-1',
    databaseURL: 'https://book-companion-1-default-rtdb.firebaseio.com',
    storageBucket: 'book-companion-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD799zvlIz71Y5cx_PrFOCb33QdVuvol04',
    appId: '1:295285705008:ios:03a5bee5d9e2845c6b60f5',
    messagingSenderId: '295285705008',
    projectId: 'book-companion-1',
    databaseURL: 'https://book-companion-1-default-rtdb.firebaseio.com',
    storageBucket: 'book-companion-1.firebasestorage.app',
    iosBundleId: 'com.example.bookTraders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD799zvlIz71Y5cx_PrFOCb33QdVuvol04',
    appId: '1:295285705008:ios:03a5bee5d9e2845c6b60f5',
    messagingSenderId: '295285705008',
    projectId: 'book-companion-1',
    databaseURL: 'https://book-companion-1-default-rtdb.firebaseio.com',
    storageBucket: 'book-companion-1.firebasestorage.app',
    iosBundleId: 'com.example.bookTraders',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB22N7QWT_hfN8CVZGrpmXTAtvSYkP83Ts',
    appId: '1:295285705008:web:b80b95931285b2ae6b60f5',
    messagingSenderId: '295285705008',
    projectId: 'book-companion-1',
    authDomain: 'book-companion-1.firebaseapp.com',
    databaseURL: 'https://book-companion-1-default-rtdb.firebaseio.com',
    storageBucket: 'book-companion-1.firebasestorage.app',
    measurementId: 'G-B175LC3P13',
  );
}
